
const GRID=.5;
let PX=72;
let currentTool='modulo';
let modules=[];
let selected=null;
let dirty=false;
let panX=120, panY=120, scale=1;
let viewMode='2d', rotX=-0.55, rotY=0.72;
let hitCache3D=[], drag3DMode=null, drag3DStart={x:0,y:0}, drag3DOrigin={x:0,y:0};
let dragging=false, panning=false, dragOff={x:0,y:0}, lastPointer={x:0,y:0};
const canvas=document.getElementById('canvas2d');
const ctx=canvas.getContext('2d');
const canvas3d=document.getElementById('canvas3d');
const ctx3d=null; // v18.1: canvas reservado para WebGL real con Three.js
const stage=document.getElementById('stage');

function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function setDirty(v=true){dirty=v;const b=document.getElementById('syncBadge');b.className='pill '+(dirty?'':'ok');b.textContent=dirty?'● Cambios pendientes':'● Sincronizado'}
function resizeCanvas(){const r=stage.getBoundingClientRect();const w=Math.max(900,Math.floor(r.width*devicePixelRatio)),h=Math.max(520,Math.floor(r.height*devicePixelRatio));canvas.width=w;canvas.height=h;canvas3d.width=w;canvas3d.height=h;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);resizeThree();drawAll()}
window.addEventListener('resize',resizeCanvas);
function snap(v){return Math.round(v/GRID)*GRID}
function worldToScreen(x,y){return {x:x*PX*scale+panX,y:y*PX*scale+panY}}
function screenToWorld(x,y){return {x:(x-panX)/(PX*scale),y:(y-panY)/(PX*scale)}}
function normalizeModule(m){return {id:m.id||Date.now()+Math.random(),tipo:m.tipo||'modulo',x:Number(m.x)||0,y:Number(m.y)||0,largo:Number(m.largo)||3,ancho:Number(m.ancho)||.73,niveles:Number(m.niveles)||3,paso:!!m.paso,sistema:m.sistema||'Europeo',estado:m.estado||'Activo',nota:m.nota||''}}
function currentSystem(){return document.getElementById('system3d')?.value||'Europeo'}
function applySystemToAll(){modules=modules.map(m=>({...m,sistema:currentSystem()}));sync();toast('Sistema 3D: '+currentSystem())}
function createLine({startX=0,startY=0,largo=12,ancho=.73,alto=6,mod=3}){const n=Math.max(1,Math.round(alto/2));const c=Math.max(1,Math.ceil(largo/mod));const arr=[];for(let i=0;i<c;i++){const rest=largo-i*mod;arr.push(normalizeModule({tipo:'modulo',sistema:currentSystem(),x:startX+i*mod,y:startY,largo:Math.min(mod,Math.max(.5,rest)),ancho,niveles:n}))}return arr}
function generateByMeasures(){const largo=parseFloat(genLargo.value||12), ancho=parseFloat(genAncho.value||.73), alto=parseFloat(genAlto.value||6), mod=parseFloat(genModulo.value||3);modules=createLine({largo,ancho,alto,mod});selected=modules[0]?.id||null;resetView(false);sync();toast('Andamio generado por medidas')}
function appendByMeasures(){const x=modules.length?Math.max(...modules.map(m=>m.x+m.largo))+1:0;const largo=parseFloat(genLargo.value||12), ancho=parseFloat(genAncho.value||.73), alto=parseFloat(genAlto.value||6), mod=parseFloat(genModulo.value||3);const arr=createLine({startX:snap(x),largo,ancho,alto,mod});modules.push(...arr);selected=arr[0]?.id||selected;sync();toast('Andamio añadido al plano')}
function generateByModules(){const cols=Math.max(1,parseInt(modCols.value||4)), levels=Math.max(1,parseInt(modLevels.value||3)), depth=Math.max(1,parseInt(modDepth.value||1)), size=parseFloat(modSize.value||3);modules=[];for(let d=0;d<depth;d++){for(let i=0;i<cols;i++){modules.push(normalizeModule({tipo:'modulo',sistema:currentSystem(),x:i*size,y:d*.85,largo:size,ancho:.73,niveles:levels}))}}selected=modules[0]?.id||null;resetView(false);sync();toast('Andamio generado por módulos')}
function appendByModules(){const x=modules.length?Math.max(...modules.map(m=>m.x+m.largo))+1:0;const cols=Math.max(1,parseInt(modCols.value||4)), levels=Math.max(1,parseInt(modLevels.value||3)), depth=Math.max(1,parseInt(modDepth.value||1)), size=parseFloat(modSize.value||3);const arr=[];for(let d=0;d<depth;d++){for(let i=0;i<cols;i++){arr.push(normalizeModule({tipo:'modulo',sistema:currentSystem(),x:snap(x+i*size),y:d*.85,largo:size,ancho:.73,niveles:levels}))}}modules.push(...arr);selected=arr[0]?.id||selected;sync();toast('Bloque de módulos añadido')}
function addModule(){const x=modules.length?Math.max(...modules.map(m=>m.x+m.largo)):0;const m=normalizeModule({tipo:'modulo',sistema:currentSystem(),x:snap(x+.5),y:0,largo:parseFloat(modSize.value||3),ancho:.73,niveles:parseInt(modLevels.value||3)});modules.push(m);selected=m.id;sync()}
function duplicateSelected(){const m=modules.find(a=>a.id===selected);if(!m){toast('Selecciona un módulo primero');return}const c=normalizeModule({...m,id:Date.now()+Math.random(),x:snap(m.x+m.largo+.5)});modules.push(c);selected=c.id;sync();toast('Módulo duplicado')}
function deleteSelected(){if(!selected)return;modules=modules.filter(m=>m.id!==selected);selected=modules[0]?.id||null;sync();toast('Módulo eliminado')}
function togglePaso(){const m=modules.find(a=>a.id===selected);if(m){m.paso=!m.paso;m.tipo=m.paso?'paso':'modulo';sync()}}
function resetView(redraw=true){panX=90;panY=140;scale=1;if(redraw)drawAll()}
function hit(wx,wy){for(let i=modules.length-1;i>=0;i--){const m=modules[i];if(m.estado==='Oculto')continue;if(wx>=m.x&&wx<=m.x+m.largo&&wy>=m.y&&wy<=m.y+m.ancho)return m}return null}
function drawGrid(w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#070a0d';ctx.fillRect(0,0,w,h);const step=Math.max(10,PX*scale*GRID);ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=1;for(let x=panX%step;x<w;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=panY%step;y<h;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='rgba(255,122,0,.45)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,panY);ctx.lineTo(w,panY);ctx.stroke();ctx.beginPath();ctx.moveTo(panX,0);ctx.lineTo(panX,h);ctx.stroke()}
function drawModule(m){if(m.estado==='Oculto')return;const p=worldToScreen(m.x,m.y), w=m.largo*PX*scale, h=m.ancho*PX*scale, sel=m.id===selected;ctx.save();ctx.fillStyle=sel?'rgba(255,122,0,.28)':(m.paso?'rgba(255,155,34,.14)':'rgba(66,165,255,.13)');ctx.strokeStyle=sel?'#ff8a12':(m.paso?'#ff9b22':'#42a5ff');ctx.lineWidth=sel?4:2;roundRect(ctx,p.x,p.y,w,h,10,true,true);ctx.strokeStyle='rgba(255,255,255,.62)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x+10,p.y+h-10);ctx.lineTo(p.x+w-10,p.y+10);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x+10,p.y+10);ctx.lineTo(p.x+w-10,p.y+h-10);ctx.stroke();const cols=Math.max(2,Math.round(m.largo/1.5)+1);ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=1;for(let i=1;i<cols;i++){const xx=p.x+w*i/cols;ctx.beginPath();ctx.moveTo(xx,p.y+4);ctx.lineTo(xx,p.y+h-4);ctx.stroke()}if(sel){drawHandles(p.x,p.y,w,h)}ctx.fillStyle='#f8fbff';ctx.font='700 12px Arial';ctx.fillText((m.paso?'PASO · ':'')+m.largo.toFixed(2)+'m · '+m.niveles+' niv.',p.x+10,p.y+21);ctx.restore()}
function drawHandles(x,y,w,h){ctx.fillStyle='#ff8a12';ctx.strokeStyle='#111';ctx.lineWidth=2;[[x,y],[x+w,y],[x,y+h],[x+w,y+h]].forEach(([a,b])=>{ctx.beginPath();ctx.arc(a,b,5,0,Math.PI*2);ctx.fill();ctx.stroke()})}
function roundRect(c,x,y,w,h,r,fill,stroke){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();if(fill)c.fill();if(stroke)c.stroke()}

function drawAll(){const w=stage.clientWidth,h=stage.clientHeight;if(viewMode==='3d')draw3D(w,h);else{drawGrid(w,h);modules.forEach(drawModule)}}
function setViewMode(mode){viewMode=mode;stage.classList.toggle('view3d',mode==='3d');document.getElementById('btn2d').classList.toggle('active',mode==='2d');document.getElementById('btn3d').classList.toggle('active',mode==='3d');document.getElementById('viewLabel').textContent=mode==='3d'?'Vista 3D estable · v18.3':'Plano 2D';drawAll();toast(mode==='3d'?'3D dentro del editor: selecciona y arrastra módulos':'Vista 2D')}
function project3D(x,y,z,cx,cy,zoom){const X=x*Math.cos(rotY)-y*Math.sin(rotY);const Y=x*Math.sin(rotY)+y*Math.cos(rotY);const yy=Y*Math.cos(rotX)-z*Math.sin(rotX);return{x:cx+X*zoom,y:cy+yy*zoom,depth:Y+z*.08}}
function line3D(a,b,color='rgba(235,241,248,.85)',lw=2){ctx3d.strokeStyle=color;ctx3d.lineWidth=lw;ctx3d.lineCap='round';ctx3d.beginPath();ctx3d.moveTo(a.x,a.y);ctx3d.lineTo(b.x,b.y);ctx3d.stroke()}
function tube3D(a,b,color,lw=4,glow=2){ctx3d.save();ctx3d.shadowColor=color;ctx3d.shadowBlur=glow;line3D(a,b,color,lw);ctx3d.restore()}
function dot3D(p,r,color){ctx3d.save();ctx3d.fillStyle=color;ctx3d.shadowColor=color;ctx3d.shadowBlur=4;ctx3d.beginPath();ctx3d.arc(p.x,p.y,r,0,Math.PI*2);ctx3d.fill();ctx3d.restore()}
function rosette3D(p,r,color){ctx3d.save();ctx3d.translate(p.x,p.y);ctx3d.fillStyle=color;ctx3d.strokeStyle='rgba(25,28,32,.8)';ctx3d.lineWidth=1;ctx3d.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4;const rr=i%2?r*.72:r;ctx3d.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx3d.closePath();ctx3d.fill();ctx3d.stroke();ctx3d.restore()}
function poly3D(points,fill,stroke='rgba(255,255,255,.25)'){ctx3d.beginPath();points.forEach((p,i)=>i?ctx3d.lineTo(p.x,p.y):ctx3d.moveTo(p.x,p.y));ctx3d.closePath();ctx3d.fillStyle=fill;ctx3d.fill();ctx3d.strokeStyle=stroke;ctx3d.lineWidth=1;ctx3d.stroke()}
function drawGround3D(minX,maxX,minY,maxY,cx,cy,zoom){for(let i=Math.floor(minX)-2;i<=Math.ceil(maxX)+2;i++){line3D(project3D(i,minY-2,0,cx,cy,zoom),project3D(i,maxY+2,0,cx,cy,zoom),'rgba(255,255,255,.045)',1)}for(let j=Math.floor(minY)-2;j<=Math.ceil(maxY)+2;j++){line3D(project3D(minX-2,j,0,cx,cy,zoom),project3D(maxX+2,j,0,cx,cy,zoom),'rgba(255,255,255,.045)',1)}line3D(project3D(minX-1,0,0,cx,cy,zoom),project3D(maxX+1,0,0,cx,cy,zoom),'rgba(255,122,0,.24)',2)}
function drawPlatform(m,z,cx,cy,zoom,sel){const a=project3D(m.x,m.y,z,cx,cy,zoom),b=project3D(m.x+m.largo,m.y,z,cx,cy,zoom),c=project3D(m.x+m.largo,m.y+m.ancho,z,cx,cy,zoom),d=project3D(m.x,m.y+m.ancho,z,cx,cy,zoom);poly3D([a,b,c,d],sel?'rgba(255,122,0,.24)':'rgba(123,145,164,.26)',sel?'rgba(255,138,18,.88)':'rgba(200,210,220,.42)');const boards=Math.max(2,Math.round(m.ancho/.28));for(let i=1;i<boards;i++){const y=m.y+(m.ancho*i/boards);line3D(project3D(m.x,y,z+.015,cx,cy,zoom),project3D(m.x+m.largo,y,z+.015,cx,cy,zoom),'rgba(255,255,255,.13)',1)}const ribs=Math.max(2,Math.round(m.largo/.5));for(let i=1;i<ribs;i++){const x=m.x+(m.largo*i/ribs);line3D(project3D(x,m.y,z+.018,cx,cy,zoom),project3D(x,m.y+m.ancho,z+.018,cx,cy,zoom),'rgba(20,24,28,.22)',1)}}
function drawToeBoard(m,z,cx,cy,zoom,sel){const color=sel?'rgba(255,122,0,.95)':'rgba(196,124,45,.86)';for(const y of [m.y,m.y+m.ancho]){tube3D(project3D(m.x,y,z+.12,cx,cy,zoom),project3D(m.x+m.largo,y,z+.12,cx,cy,zoom),color,4,1)}}
function drawBaseJack(x,y,cx,cy,zoom,sel){const c=sel?'#ff8a12':'#c5ccd3';tube3D(project3D(x,y,-.22,cx,cy,zoom),project3D(x,y,.20,cx,cy,zoom),c,3,1);poly3D([project3D(x-.20,y-.13,-.22,cx,cy,zoom),project3D(x+.20,y-.13,-.22,cx,cy,zoom),project3D(x+.20,y+.13,-.22,cx,cy,zoom),project3D(x-.20,y+.13,-.22,cx,cy,zoom)],'rgba(196,203,210,.38)','rgba(255,255,255,.25)')}
function registerHit3D(m,cx,cy,zoom){const zTop=(m.niveles||1)*2;const pts=[project3D(m.x,m.y,0,cx,cy,zoom),project3D(m.x+m.largo,m.y,0,cx,cy,zoom),project3D(m.x+m.largo,m.y+m.ancho,0,cx,cy,zoom),project3D(m.x,m.y+m.ancho,0,cx,cy,zoom),project3D(m.x,m.y,zTop,cx,cy,zoom),project3D(m.x+m.largo,m.y,zTop,cx,cy,zoom),project3D(m.x+m.largo,m.y+m.ancho,zTop,cx,cy,zoom),project3D(m.x,m.y+m.ancho,zTop,cx,cy,zoom)];hitCache3D.push({id:m.id,minX:Math.min(...pts.map(p=>p.x))-14,maxX:Math.max(...pts.map(p=>p.x))+14,minY:Math.min(...pts.map(p=>p.y))-14,maxY:Math.max(...pts.map(p=>p.y))+14,depth:Math.max(...pts.map(p=>p.depth))})}
function hit3D(x,y){for(const h of [...hitCache3D].sort((a,b)=>b.depth-a.depth)){if(x>=h.minX&&x<=h.maxX&&y>=h.minY&&y<=h.maxY)return modules.find(m=>m.id===h.id)}return null}
function drawFrameSystem(m,cx,cy,zoom){const sel=m.id===selected, main=sel?'#ff8a12':'#edf2f5',rail=sel?'rgba(255,155,34,.96)':'rgba(222,231,238,.78)',diag=sel?'rgba(255,122,0,.96)':'rgba(126,165,205,.82)',toe=sel?'rgba(255,122,0,.95)':'rgba(189,118,45,.86)',zTop=(m.niveles||1)*2;const xs=[m.x,m.x+m.largo],ys=[m.y,m.y+m.ancho];registerHit3D(m,cx,cy,zoom);for(const x of xs){for(const y of ys){drawBaseJack(x,y,cx,cy,zoom,sel);tube3D(project3D(x,y,0,cx,cy,zoom),project3D(x,y,zTop+.24,cx,cy,zoom),main,5,sel?7:2)}}for(let lvl=0;lvl<=m.niveles;lvl++){const z=lvl*2;for(const y of ys){tube3D(project3D(m.x,y,z,cx,cy,zoom),project3D(m.x+m.largo,y,z,cx,cy,zoom),rail,4,2);if(lvl<m.niveles){tube3D(project3D(m.x,y,z+1,cx,cy,zoom),project3D(m.x+m.largo,y,z+1,cx,cy,zoom),'rgba(210,220,230,.52)',2,1)}}for(const x of xs){tube3D(project3D(x,m.y,z,cx,cy,zoom),project3D(x,m.y+m.ancho,z,cx,cy,zoom),rail,3,1)}if(lvl>0){drawPlatform(m,z-.06,cx,cy,zoom,sel);drawToeBoard(m,z,cx,cy,zoom,sel)}}for(let lvl=0;lvl<m.niveles;lvl++){const z=lvl*2,z2=(lvl+1)*2;for(const y of ys){tube3D(project3D(m.x,y,z,cx,cy,zoom),project3D(m.x+m.largo,y,z2,cx,cy,zoom),diag,2.5,1);tube3D(project3D(m.x+m.largo,y,z,cx,cy,zoom),project3D(m.x,y,z2,cx,cy,zoom),diag,2.5,1)}}for(let lvl=0;lvl<m.niveles;lvl++){const z=lvl*2;for(const x of xs){for(let r=.45;r<1.85;r+=.45){tube3D(project3D(x,m.y,z+r,cx,cy,zoom),project3D(x,m.y+m.ancho,z+r,cx,cy,zoom),'rgba(238,244,248,.55)',1.4,0)}}}if(m.paso){const z=2;tube3D(project3D(m.x+.22,m.y,z,cx,cy,zoom),project3D(m.x+m.largo-.22,m.y,z,cx,cy,zoom),'#ff9b22',6,5);tube3D(project3D(m.x+.22,m.y+m.ancho,z,cx,cy,zoom),project3D(m.x+m.largo-.22,m.y+m.ancho,z,cx,cy,zoom),'#ff9b22',6,5)}}
function drawRinglockSystem(m,cx,cy,zoom){const sel=m.id===selected, main=sel?'#ff8a12':'#e5edf3',rail=sel?'rgba(255,155,34,.96)':'rgba(218,228,236,.80)',diag=sel?'rgba(255,122,0,.96)':'rgba(155,190,220,.82)',node=sel?'#ffb04a':'#9fb0bf',zTop=(m.niveles||1)*2;const xs=[m.x,m.x+m.largo],ys=[m.y,m.y+m.ancho];registerHit3D(m,cx,cy,zoom);for(const x of xs){for(const y of ys){drawBaseJack(x,y,cx,cy,zoom,sel);tube3D(project3D(x,y,0,cx,cy,zoom),project3D(x,y,zTop+.25,cx,cy,zoom),main,4.5,sel?7:2);for(let z=0;z<=zTop+.01;z+=.5){rosette3D(project3D(x,y,z,cx,cy,zoom),3.5,node)}}}for(let lvl=0;lvl<=m.niveles;lvl++){const z=lvl*2;for(const y of ys){tube3D(project3D(m.x,y,z,cx,cy,zoom),project3D(m.x+m.largo,y,z,cx,cy,zoom),rail,3.5,2)}for(const x of xs){tube3D(project3D(x,m.y,z,cx,cy,zoom),project3D(x,m.y+m.ancho,z,cx,cy,zoom),rail,3.5,2)}if(lvl>0){drawPlatform(m,z-.06,cx,cy,zoom,sel);drawToeBoard(m,z,cx,cy,zoom,sel)}if(lvl<m.niveles){const zMid=z+1;for(const y of ys){tube3D(project3D(m.x,y,zMid,cx,cy,zoom),project3D(m.x+m.largo,y,zMid,cx,cy,zoom),'rgba(210,220,230,.46)',2,1)}}}for(let lvl=0;lvl<m.niveles;lvl++){const z=lvl*2,z2=(lvl+1)*2;tube3D(project3D(m.x,m.y,z,cx,cy,zoom),project3D(m.x+m.largo,m.y+m.ancho,z2,cx,cy,zoom),diag,2.4,1);tube3D(project3D(m.x+m.largo,m.y,z,cx,cy,zoom),project3D(m.x,m.y+m.ancho,z2,cx,cy,zoom),diag,2.4,1);tube3D(project3D(m.x,m.y+m.ancho,z,cx,cy,zoom),project3D(m.x+m.largo,m.y,z2,cx,cy,zoom),'rgba(140,170,202,.58)',1.8,0)}}
let threeReady=false, threeScene=null, threeCamera=null, threeRenderer=null, threeControls=null, threeRoot=null, threeRaycaster=null, threeMouse=null, threeDrag=null, threePlane=null, threeNeedsBuild=true;
const THREE_MATERIALS={};
function ensureThree(){
  if(threeReady || !window.THREE || !THREE.OrbitControls) return threeReady;
  threeScene=new THREE.Scene();
  threeScene.background=new THREE.Color(0x06080b);
  threeCamera=new THREE.PerspectiveCamera(45,1,.1,1000);
  threeCamera.up.set(0,0,1);threeCamera.position.set(7,-9,6.2);
  threeRenderer=new THREE.WebGLRenderer({canvas:canvas3d,antialias:true,alpha:false,powerPreference:'high-performance'});
  threeRenderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));
  threeRenderer.shadowMap.enabled=true;
  threeRenderer.shadowMap.type=THREE.PCFSoftShadowMap;
  threeControls=new THREE.OrbitControls(threeCamera,canvas3d);
  threeControls.enableDamping=true;
  threeControls.dampingFactor=.08;
  threeControls.screenSpacePanning=true;
  threeControls.minDistance=3;
  threeControls.maxDistance=70;
  threeControls.maxPolarAngle=Math.PI*.49;threeControls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
  threeRaycaster=new THREE.Raycaster();
  threeMouse=new THREE.Vector2();
  threePlane=new THREE.Plane(new THREE.Vector3(0,0,1),0);
  THREE_MATERIALS.galv=new THREE.MeshStandardMaterial({color:0xc7d0d8,metalness:.72,roughness:.28});
  THREE_MATERIALS.darkGalv=new THREE.MeshStandardMaterial({color:0x8f9aa3,metalness:.78,roughness:.32});
  THREE_MATERIALS.orange=new THREE.MeshStandardMaterial({color:0xff7a00,metalness:.35,roughness:.25,emissive:0x2a1100});
  THREE_MATERIALS.platform=new THREE.MeshStandardMaterial({color:0x6d7680,metalness:.65,roughness:.38});
  THREE_MATERIALS.wood=new THREE.MeshStandardMaterial({color:0x8a6038,metalness:.05,roughness:.62});
  THREE_MATERIALS.node=new THREE.MeshStandardMaterial({color:0x303941,metalness:.8,roughness:.24});
  THREE_MATERIALS.floor=new THREE.MeshStandardMaterial({color:0x101418,metalness:.15,roughness:.7});
  const hemi=new THREE.HemisphereLight(0xffffff,0x17191d,1.25);threeScene.add(hemi);
  const key=new THREE.DirectionalLight(0xffffff,1.75);key.position.set(5,-7,10);key.castShadow=true;key.shadow.mapSize.set(1024,1024);threeScene.add(key);
  const rim=new THREE.DirectionalLight(0xff7a00,.45);rim.position.set(-6,5,4);threeScene.add(rim);
  threeRoot=new THREE.Group();threeScene.add(threeRoot);
  const grid=new THREE.GridHelper(80,80,0xff7a00,0x26313a);grid.rotation.x=Math.PI/2;grid.material.opacity=.22;grid.material.transparent=true;threeScene.add(grid);
  animateThree();threeReady=true;resizeThree();return true;
}
function resizeThree(){if(!threeRenderer||!threeCamera)return;const r=stage.getBoundingClientRect();const w=Math.max(1,r.width),h=Math.max(1,r.height);threeRenderer.setSize(w,h,false);threeCamera.aspect=w/h;threeCamera.updateProjectionMatrix();}
function animateThree(){requestAnimationFrame(animateThree);if(!threeReady)return;if(threeControls)threeControls.update();if(threeRenderer)threeRenderer.render(threeScene,threeCamera)}
function clearThreeRoot(){if(!threeRoot)return;while(threeRoot.children.length){const o=threeRoot.children.pop();o.traverse?.(c=>{if(c.geometry)c.geometry.dispose?.()});}}
function tagModuleMeshes(group,id){group.traverse(o=>{o.userData=o.userData||{};o.userData.moduleId=id;});return group}
function safeThreeError(msg){const c=canvas3d.getContext('2d');const w=stage.clientWidth,h=stage.clientHeight;c.clearRect(0,0,w,h);c.fillStyle='#06080b';c.fillRect(0,0,w,h);c.fillStyle='#ff9b22';c.font='900 18px Arial';c.fillText('3D no iniciado',30,48);c.fillStyle='#d8dee5';c.font='700 13px Arial';c.fillText(msg||'Revisa consola o conexión a Three.js.',30,76);}
function matFor(m,base){return m.id===selected?THREE_MATERIALS.orange:base}
function tubeBetween(a,b,r,mat,segments=12){const va=new THREE.Vector3(a[0],a[1],a[2]),vb=new THREE.Vector3(b[0],b[1],b[2]);const mid=va.clone().add(vb).multiplyScalar(.5);const len=va.distanceTo(vb);const geo=new THREE.CylinderGeometry(r,r,len,segments);const mesh=new THREE.Mesh(geo,mat);mesh.position.copy(mid);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),vb.clone().sub(va).normalize());mesh.castShadow=true;mesh.receiveShadow=true;return mesh}
function boxPart(x,y,z,w,d,h,mat){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,d,h),mat);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;return mesh}
function addPlatform(group,m,z,mat){const parts=Math.max(2,Math.round(m.ancho/.32));for(let i=0;i<parts;i++){const y=m.y+(i+.5)*m.ancho/parts;group.add(boxPart(m.x+m.largo/2,y,z,m.largo-.08,m.ancho/parts-.035,.08,mat));}for(let x=m.x+.35;x<m.x+m.largo;x+=.55){group.add(boxPart(x,m.y+m.ancho/2,z+.055,.035,m.ancho,.045,THREE_MATERIALS.darkGalv));}}
function addBaseJack(group,x,y,sel){const mat=sel?THREE_MATERIALS.orange:THREE_MATERIALS.galv;group.add(tubeBetween([x,y,-.28],[x,y,.24],.035,mat));group.add(boxPart(x,y,-.31,.42,.28,.035,mat));}
function addRosette(group,x,y,z,mat){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.CylinderGeometry(.145,.145,.025,24),mat);ring.rotation.x=Math.PI/2;g.add(ring);for(let i=0;i<8;i++){const a=i*Math.PI/4;const plate=boxPart(Math.cos(a)*.11,Math.sin(a)*.11,0,.13,.026,.018,mat);plate.rotation.z=a;g.add(plate)}g.position.set(x,y,z);group.add(g)}
function makeModuleGroup(m){const g=new THREE.Group();g.userData.moduleId=m.id;const sel=m.id===selected;const top=(m.niveles||1)*2;const xs=[m.x,m.x+m.largo],ys=[m.y,m.y+m.ancho];const main=matFor(m,THREE_MATERIALS.galv), rail=matFor(m,THREE_MATERIALS.darkGalv), diag=matFor(m,THREE_MATERIALS.darkGalv);
  if((m.sistema||currentSystem())==='Multidireccional'){
    for(const x of xs)for(const y of ys){addBaseJack(g,x,y,sel);g.add(tubeBetween([x,y,0],[x,y,top+.28],.045,main));for(let z=0;z<=top+.01;z+=.5)addRosette(g,x,y,z,sel?THREE_MATERIALS.orange:THREE_MATERIALS.node)}
    for(let lvl=0;lvl<=m.niveles;lvl++){const z=lvl*2;for(const y of ys)g.add(tubeBetween([m.x,y,z],[m.x+m.largo,y,z],.038,rail));for(const x of xs)g.add(tubeBetween([x,m.y,z],[x,m.y+m.ancho,z],.038,rail));if(lvl>0){addPlatform(g,m,z-.08,THREE_MATERIALS.platform);for(const y of ys)g.add(boxPart(m.x+m.largo/2,y,z+.18,m.largo,.055,.18,THREE_MATERIALS.wood));}}
    for(let lvl=0;lvl<m.niveles;lvl++){const z=lvl*2,z2=(lvl+1)*2;g.add(tubeBetween([m.x,m.y,z],[m.x+m.largo,m.y+m.ancho,z2],.025,diag));g.add(tubeBetween([m.x+m.largo,m.y,z],[m.x,m.y+m.ancho,z2],.025,diag));}
  }else{
    const frameStep=2.5;let frameXs=[];for(let x=m.x;x<=m.x+m.largo+.01;x+=frameStep)frameXs.push(Math.min(x,m.x+m.largo));if(frameXs[frameXs.length-1]!==m.x+m.largo)frameXs.push(m.x+m.largo);
    for(const x of frameXs)for(const y of ys){addBaseJack(g,x,y,sel);g.add(tubeBetween([x,y,0],[x,y,top+.22],.052,main));for(let lvl=0;lvl<=m.niveles;lvl++){const z=lvl*2;g.add(tubeBetween([x,m.y,z],[x,m.y+m.ancho,z],.04,rail));if(lvl<m.niveles){g.add(tubeBetween([x,m.y,z+.55],[x,m.y+m.ancho,z+.55],.026,rail));g.add(tubeBetween([x,m.y,z+1.05],[x,m.y+m.ancho,z+1.05],.026,rail));}}}
    for(let lvl=0;lvl<=m.niveles;lvl++){const z=lvl*2;for(const y of ys)g.add(tubeBetween([m.x,y,z],[m.x+m.largo,y,z],.038,rail));if(lvl>0){addPlatform(g,m,z-.08,THREE_MATERIALS.platform);for(const y of ys)g.add(boxPart(m.x+m.largo/2,y,z+.17,m.largo,.055,.18,THREE_MATERIALS.wood));}}
    for(let lvl=0;lvl<m.niveles;lvl++){const z=lvl*2,z2=(lvl+1)*2;for(const y of ys){g.add(tubeBetween([m.x,y,z],[m.x+m.largo,y,z2],.026,diag));g.add(tubeBetween([m.x+m.largo,y,z],[m.x,y,z2],.026,diag));}}
  }
  const box=new THREE.Box3().setFromObject(g);g.userData.box=box;return tagModuleMeshes(g,m.id);
}
function rebuildThree(){if(!ensureThree())return;clearThreeRoot();const floor=boxPart(0,0,-.34,80,80,.02,THREE_MATERIALS.floor);floor.receiveShadow=true;floor.userData.ignorePick=true;threeRoot.add(floor);modules.filter(m=>m.estado!=='Oculto').forEach(m=>threeRoot.add(makeModuleGroup(m)));fitCameraToScaffold();threeNeedsBuild=false;}
function fitCameraToScaffold(){const active=modules.filter(m=>m.estado!=='Oculto');if(!active.length)return;const minX=Math.min(...active.map(m=>m.x)),maxX=Math.max(...active.map(m=>m.x+m.largo)),minY=Math.min(...active.map(m=>m.y)),maxY=Math.max(...active.map(m=>m.y+m.ancho)),maxZ=Math.max(...active.map(m=>(m.niveles||1)*2));const cx=(minX+maxX)/2,cy=(minY+maxY)/2,cz=maxZ/2;threeControls.target.set(cx,cy,cz);if(!threeCamera.userData.fitted){threeCamera.position.set(cx+6,cy-8,Math.max(4,cz+5));threeCamera.userData.fitted=true}}
function draw3D(w,h){try{if(!window.THREE || !THREE.OrbitControls){safeThreeError('Cargando Three.js desde CDN... Si tarda, revisa conexión.');setTimeout(()=>{if(viewMode==='3d')drawAll()},800);return}ensureThree();rebuildThree();}catch(err){console.error('[KAYN 3D]',err);safeThreeError(err.message||'Error interno del motor 3D');}}
function setMouse3D(e){const r=canvas3d.getBoundingClientRect();threeMouse.x=((e.clientX-r.left)/r.width)*2-1;threeMouse.y=-((e.clientY-r.top)/r.height)*2+1;}
function pickModule3D(e){if(!ensureThree())return null;setMouse3D(e);threeRaycaster.setFromCamera(threeMouse,threeCamera);const hits=threeRaycaster.intersectObjects(threeRoot.children,true);for(const h of hits){let o=h.object;if(o.userData?.ignorePick)continue;while(o&&o!==threeRoot){if(o.userData?.moduleId)return modules.find(m=>m.id===o.userData.moduleId);o=o.parent}}return null}
function intersectGround3D(e){setMouse3D(e);threeRaycaster.setFromCamera(threeMouse,threeCamera);const p=new THREE.Vector3();threeRaycaster.ray.intersectPlane(threePlane,p);return p}


function calcBreakdown(){const bd={};const add=(k,q,w=0)=>{if(!bd[k])bd[k]={qty:0,weight:0};bd[k].qty+=Math.round(q);bd[k].weight+=Math.round(q*w*10)/10};modules.forEach(m=>{if(m.estado==='Oculto')return;const len=m.largo.toFixed(2)+' m',n=Number(m.niveles)||1;if(m.paso)add('Marcos de paso '+len,1,18);else add('Marcos europeos 2.00 m',2*n,16);add('Plataformas '+len,n,22);add('Diagonales '+len,n,6);add('Barandillas '+len,n*2,5);add('Rodapiés '+len,n,4);add('Husillos / bases',2,4.5)});return bd}
function renderBreakdown(){const bd=calcBreakdown(),rows=Object.entries(bd).sort((a,b)=>a[0].localeCompare(b[0]));const totalQty=rows.reduce((a,r)=>a+r[1].qty,0),totalWeight=rows.reduce((a,r)=>a+r[1].weight,0);breakdown.innerHTML='<table class="miniTable"><tr><th>Pieza</th><th>Cantidad</th><th>Peso aprox.</th></tr>'+rows.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1].qty+'</td><td>'+r[1].weight.toFixed(1)+' kg</td></tr>').join('')+'</table><p style="color:#9da8b4;font-weight:800">Total: '+totalQty+' piezas · '+totalWeight.toFixed(1)+' kg</p>';mPieces.textContent=totalQty}
function toggleBreakdown(){breakdownDrawer.classList.toggle('active')}
function updateStats(){const area=modules.reduce((a,m)=>a+m.largo*m.ancho*(m.niveles||1),0);const maxN=modules.reduce((a,m)=>Math.max(a,m.niveles||1),0);mMods.textContent=modules.length;mArea.textContent=area.toFixed(2)+' m²';mLevels.textContent=maxN;mSel.textContent=selected?'Seleccionado':'Ninguno'}
function renderProps(){const m=modules.find(a=>a.id===selected);inspector.classList.toggle('active',!!m);if(!m)return;propTipo.value=m.tipo;propLargo.value=m.largo;propAncho.value=m.ancho;propNiveles.value=m.niveles;propX.value=m.x;propY.value=m.y;propNota.value=m.nota||''}
function updateSelectedFromProps(){const m=modules.find(a=>a.id===selected);if(!m)return;m.tipo=propTipo.value;m.largo=parseFloat(propLargo.value||m.largo);m.ancho=parseFloat(propAncho.value||m.ancho);m.niveles=parseInt(propNiveles.value||m.niveles);m.x=snap(parseFloat(propX.value||m.x));m.y=snap(parseFloat(propY.value||m.y));m.nota=propNota.value||'';m.paso=m.tipo==='paso';sync()}
function sync(){modules=modules.map(normalizeModule);localStorage.kaynEditorModulos=JSON.stringify({modules});coreSync();drawAll();renderProps();renderBreakdown();updateStats();setDirty(true)}
function saveProject(){localStorage.kaynEditorModulos=JSON.stringify({modules});coreSync();setDirty(false);toast('Proyecto guardado')}
function coreSync(){window.coreEngine=window.coreEngine||{version:'18.3',project:{id:'kayn-'+Date.now(),name:'Proyecto KAYN',updatedAt:new Date().toISOString()},modules:[],selection:[],breakdown:{},settings:{system:currentSystem()},history:[]};window.coreEngine.version='18.3';window.coreEngine.modules=modules;window.coreEngine.selection=selected?[selected]:[];window.coreEngine.settings={...(window.coreEngine.settings||{}),system:currentSystem()};window.coreEngine.project.updatedAt=new Date().toISOString();localStorage.kaynCoreEngine=JSON.stringify(window.coreEngine)}
function coreLoad(){try{const saved=JSON.parse(localStorage.kaynCoreEngine||'null');if(saved&&Array.isArray(saved.modules)&&saved.modules.length){window.coreEngine=saved;modules=saved.modules.map(normalizeModule);selected=saved.selection?.[0]||modules[0]?.id||null;return true}}catch(e){}try{const p=JSON.parse(localStorage.kaynEditorModulos||'{}');if(Array.isArray(p.modules)&&p.modules.length){modules=p.modules.map(normalizeModule);selected=modules[0]?.id||null;return true}}catch(e){}return false}
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('pointerdown',e=>{const p=pos(e),w=screenToWorld(p.x,p.y),m=hit(w.x,w.y);lastPointer=p;if(m){selected=m.id;dragging=true;dragOff.x=w.x-m.x;dragOff.y=w.y-m.y;stage.classList.add('dragging');sync()}else{selected=null;panning=true;renderProps();drawAll();updateStats()}canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{const p=pos(e);if(dragging){const w=screenToWorld(p.x,p.y),m=modules.find(a=>a.id===selected);if(m){m.x=snap(w.x-dragOff.x);m.y=snap(w.y-dragOff.y);sync()}}else if(panning){panX+=p.x-lastPointer.x;panY+=p.y-lastPointer.y;drawAll()}lastPointer=p});
canvas.addEventListener('pointerup',e=>{dragging=false;panning=false;stage.classList.remove('dragging');try{canvas.releasePointerCapture(e.pointerId)}catch(_){}});
canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e),before=screenToWorld(p.x,p.y);scale=Math.max(.35,Math.min(3.2,scale*(e.deltaY<0?1.08:.92)));const after=screenToWorld(p.x,p.y);panX+=(after.x-before.x)*PX*scale;panY+=(after.y-before.y)*PX*scale;drawAll()},{passive:false});
window.addEventListener('keydown',e=>{if(e.key==='Delete')deleteSelected();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}});

canvas3d.addEventListener('pointerdown',e=>{if(!ensureThree())return;const m=pickModule3D(e);lastPointer=pos3d(e);if(m){selected=m.id;const p=intersectGround3D(e);drag3DMode='move';drag3DStart=p;drag3DOrigin={x:m.x,y:m.y};threeControls.enabled=false;stage.classList.add('dragging');renderProps();updateStats();rebuildThree();toast('Módulo seleccionado en 3D')}else{drag3DMode='orbit';threeControls.enabled=true}canvas3d.setPointerCapture(e.pointerId)});
canvas3d.addEventListener('pointermove',e=>{if(drag3DMode==='move'){const m=modules.find(a=>a.id===selected);const p=intersectGround3D(e);if(m&&p&&drag3DStart){m.x=snap(drag3DOrigin.x+(p.x-drag3DStart.x));m.y=snap(drag3DOrigin.y+(p.y-drag3DStart.y));modules=modules.map(normalizeModule);localStorage.kaynEditorModulos=JSON.stringify({modules});coreSync();renderProps();renderBreakdown();updateStats();setDirty(true);rebuildThree();}}});
canvas3d.addEventListener('pointerup',e=>{drag3DMode=null;threeControls&&(threeControls.enabled=true);stage.classList.remove('dragging');try{canvas3d.releasePointerCapture(e.pointerId)}catch(_){};drawAll();});
canvas3d.addEventListener('wheel',e=>{}, {passive:true});
function pos3d(e){const r=canvas3d.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
if(location.hash==='#3d'){setTimeout(()=>setViewMode('3d'),350)}
window.addEventListener('load',()=>{resizeCanvas();if(viewMode==='3d')drawAll();});

window.addEventListener('beforeunload',coreSync);
coreLoad();try{const saved=JSON.parse(localStorage.kaynCoreEngine||'null');if(saved?.settings?.system&&document.getElementById('system3d'))document.getElementById('system3d').value=saved.settings.system}catch(e){}if(!modules.length)generateByMeasures();resizeCanvas();sync();setDirty(false);
